version: "3.8"

volumes:
  postgres-data:

networks:
  net:

services:
  postgres:
    container_name: postgres-sh-scripts
    image: postgres:15
    env_file:
      - ../.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5437:5432"
    networks:
      - net
